services:
  spring-rtc:
    container_name: chatty-birds-server-spring
    image: chatty-birds-spring:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - '8080:8080'
